# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.62485874 0.60503987 0.39972688 ... 0.0846351  0.69686413 0.54732892]
 [0.4634057  0.45915178 0.68127701 ... 0.97827484 0.79191262 0.21808352]
 [0.8547806  0.68153166 0.58206725 ... 0.28456214 0.80453299 0.83560723]
 ...
 [0.55643856 0.05587637 0.00872116 ... 0.84900806 0.19507287 0.49651817]
 [0.76458857 0.87535627 0.85700972 ... 0.20165115 0.66984597 0.61105774]
 [0.9379917  0.90602652 0.48644874 ... 0.45478997 0.30802045 0.64411891]]
[[0.05898571 0.77145501 0.93235888 ... 0.25481956 0.5784935  0.84138357]
 [0.83973178 0.89953419 0.36023266 ... 0.08171528 0.56878015 0.10667091]
 [0.47102931 0.04482554 0.91632494 ... 0.94637669 0.50959818 0.61719054]
 ...
 [0.82815532 0.90218506 0.77838013 ... 0.39851499 0.73064725 0.52476429]
 [0.20878136 0.02406234 0.19306379 ... 0.59425444 0.18259171 0.54238335]
 [0.60597163 0.24419025 0.03767618 ... 0.65168803 0.83792257 0.6070072 ]]


Без использования numpy

In [4]:
def mult(a, b):
    s = len(a)
    result = [[0 for _ in range(s)] for _ in range(s)]
    for i in range(s):
        for j in range(s):
            for k in range(s):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [5]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 708 ms, sys: 2.69 ms, total: 710 ms
Wall time: 716 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 747 µs, sys: 92 µs, total: 839 µs
Wall time: 3.2 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.553956963107339e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.58629114 0.42499001 0.76209113] [0.02120471 0.83506598 0.6948715 ]


In [10]:
def scalar_product(a,b):
    s = 0
    s = sum(a[i] * b[i] for i in range(3))
    return s

In [11]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [12]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 22.4 µs
CPU times: user 0 ns, sys: 451 µs, total: 451 µs
Wall time: 366 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy оказываются эффективнее благодаря реализации на языке C, векторизации операций, оптимизированным алгоритмам, низкоуровневой работе с памятью. Благодар этому вычислений в NumPy высока, что делает его предпочтительным выбором для вычислений и обработки данных в Python.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [18]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  if len(a) > 0 and len(a[0]) == len(a):
    diagonal = np.diagonal(a)
    even_diagonal = diagonal[diagonal % 2 == 0]
    return np.sum(even_diagonal)
  else:
    return 0

In [16]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 7, 9, 9, 6],
       [8, 1, 9, 7, 3],
       [9, 3, 8, 2, 5],
       [6, 8, 3, 5, 1],
       [1, 2, 6, 6, 8]])

In [19]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 168 µs, sys: 23 µs, total: 191 µs
Wall time: 198 µs


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [20]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumulative_sums = np.cumsum(X, axis=1)
    result = cumulative_sums / np.arange(1, X.shape[1] + 1)
    return result

In [21]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[6.40325001e-02 9.35260312e-01 6.41222479e-01 5.19192576e-01
 4.08553665e-01 1.40208906e-03 8.93817201e-02 7.95662579e-01
 5.85410549e-01 3.58201802e-02 3.70391757e-01 9.74433526e-01
 6.02371922e-01 5.07510382e-01 3.61872399e-01 3.67233238e-01
 5.01938226e-01 2.92807114e-01 8.06592309e-02 3.06896031e-01
 3.65056979e-01 5.84631464e-01 9.37007638e-02 6.54336465e-01
 6.02596435e-01 2.69528214e-01 2.31383182e-01 5.09198418e-01
 7.10853754e-01 6.90103691e-01 7.32470482e-01 7.63304254e-01
 8.70142968e-01 6.18908908e-01 1.65464947e-01 4.22655246e-01
 3.03667881e-01 3.51733824e-01 1.72704443e-01 9.36361229e-01
 4.59972903e-01 8.22090369e-01 2.57371931e-01 5.85482243e-01
 3.65170590e-01 4.96573940e-01 9.39871303e-01 7.73302303e-01
 1.95598291e-01 6.83940585e-02 2.41004329e-01 6.29188770e-02
 5.26879011e-01 1.91630796e-01 5.04105786e-01 4.54958331e-01
 7.88172686e-01 3.54504079e-01 9.98132620e-01 4.65829039e-01
 2.38002409e-01 6.60124234e-01 4.53797244e-01 7.79758582e-01
 3.19286953e-01 2.959300

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [29]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    elements = []
    counts = []

    current_element = a[0]
    current_count = 1

    for i in range(1, len(a)):
        if a[i] == current_element:
            current_count += 1
        else:
            elements.append(current_element)
            counts.append(current_count)
            current_element = a[i]
            current_count = 1

    elements.append(current_element)
    counts.append(current_count)

    result = np.array(elements), np.array(counts)
    return result

In [30]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(np_encode(X))

CPU times: user 33 µs, sys: 5 µs, total: 38 µs
Wall time: 41 µs
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [32]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transform_X = X.copy()

    transform_X[1::2] = a

    transform_X[::2] = transform_X[::2] ** 3

    reversed_transform_X = transform_X[::-1]

    result = np.concatenate((X, reversed_transform_X))

    return result

In [33]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(np_transformation(X, 5))

CPU times: user 1.18 ms, sys: 12 µs, total: 1.2 ms
Wall time: 1.35 ms
[  1   3   5   7   9 729   5 125   5   1]
